name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    # Note 1: the JDK gets automatically downloaded
    # Note 2: caching is enabled automatically by `setup-gradle`

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Run tests
      run: ./gradlew check
